### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by bjornharrtell** [bjornharrtell/pgadmin3#1]
## TODOs

* [ ] Get it to work with PostgreSQL 10
* [ ] Get it to work with wxWidgets 3.0 and GTK+ 3
* [ ] Get it to work with wxWidgets 3.1 (many bugs solved, new Scintilla editor etc.)
* [ ] Fix graphical issues on GTK 3 dark theme (icon transparency, STC styling)
* [ ] Fix use of deprecated indicator styling for STC 
* [ ] Fix GTK+ 3 warnings
* [ ] Improve connection timeout/closed error handling
* [ ] Get maintainership to allow new versions to reach Debian and other dists

## Controversial
* [ ]  ? Drop less useful but complex features (graphical query editor, graphical explain, scratch pad)
* [ ] ? Drop Windows/Mac support
